import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { UserInfosProvider } from "@/context/UserInfos";
import { AddNewEntityProvider } from "@/context/AddNewEntityProvider";
import { AddNewEntity } from "@/Components/AddNewEntity";
import { getUserInfos } from "@/utils/getUserInfos";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = await getUserInfos() ?? undefined;
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <Toaster position="top-right"/>
        <UserInfosProvider user={user}>
          <AddNewEntityProvider>
            <AddNewEntity />
            {children}
          </AddNewEntityProvider>
        </UserInfosProvider>
      </body>
    </html>
  );
}
